import { ModelEntry } from "@localmind/shared-types";

export const registryModels: ModelEntry[] = [
  // ─── CHAT LLMs ─────────────────────────────────────────────────────────────
  {
    id: "meta-llama/Llama-3.2-3B-Instruct-GGUF",
    slug: "llama-3.2-3b-instruct",
    name: "Llama 3.2 3B Instruct",
    author: "Meta",
    category: "chat",
    subcategory: "chat",
    description: "Meta's lightweight instruction-tuned 3B model, highly optimized for edge devices.",
    longDescription: "Meta Llama 3.2 3B Instruct is part of the Llama 3.2 collection of multilingual models. It is designed for low-latency dialogue, instruction-following, and reasoning on resource-constrained devices like laptops and workstations.",
    tags: ["gguf", "instruction-tuned", "multilingual", "llama3.2"],
    license: "llama3.2",
    requiresAuth: false,
    variants: [
      {
        id: "meta-llama/Llama-3.2-3B-Instruct-GGUF-Q4_K_M",
        label: "Q4_K_M (Recommended - Balanced)",
        quantization: "Q4_K_M",
        sizeGB: 2.2,
        downloadUrl: "https://huggingface.co/lmstudio-community/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf",
        sha256: "8e75e9b3a3ab8570f7cf7c7c00e12ff488e001cbe651ea652b04f794de750034",
        filename: "Llama-3.2-3B-Instruct-Q4_K_M.gguf",
        contextLength: 131072,
        minVramGB: 3.5,
        recommended: true
      },
      {
        id: "meta-llama/Llama-3.2-3B-Instruct-GGUF-Q8_0",
        label: "Q8_0 (Best Quality - Heavy)",
        quantization: "Q8_0",
        sizeGB: 3.4,
        downloadUrl: "https://huggingface.co/lmstudio-community/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q8_0.gguf",
        sha256: "9f01e9d3a3ab8570f7cf7c7c00e12ff488e001cbe651ea652b04f794de750045",
        filename: "Llama-3.2-3B-Instruct-Q8_0.gguf",
        contextLength: 131072,
        minVramGB: 4.8,
        recommended: false
      }
    ],
    minRequirements: { ramGB: 8, vramGB: 0, diskGB: 4, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 16, vramGB: 4 },
    minComputeScore: 10,
    downloads: 1450000,
    likes: 12500,
    rating: 4.8,
    thumbnailUrl: "",
    createdAt: "2024-09-25T12:00:00Z",
    updatedAt: "2024-09-25T12:00:00Z",
    source: "huggingface",
    hfRepoId: "lmstudio-community/Llama-3.2-3B-Instruct-GGUF"
  },
  {
    id: "meta-llama/Llama-3.1-8B-Instruct-GGUF",
    slug: "llama-3.1-8b-instruct",
    name: "Llama 3.1 8B Instruct",
    author: "Meta",
    category: "chat",
    subcategory: "chat",
    description: "Meta's flagship 8B instruction model with 128k context window.",
    longDescription: "Llama 3.1 8B Instruct supports a 128k context window and is optimized for multilingual dialogue, code generation, and advanced reasoning tasks.",
    tags: ["gguf", "instruction-tuned", "multilingual", "llama3.1", "128k"],
    license: "llama3.1",
    requiresAuth: false,
    variants: [
      {
        id: "llama-3.1-8b-Q4_K_M",
        label: "Q4_K_M (Recommended)",
        quantization: "Q4_K_M",
        sizeGB: 4.9,
        downloadUrl: "https://huggingface.co/lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf",
        sha256: "a1b2c3d4e5f6789012345678901234567890123456789012345678901234567890",
        filename: "Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf",
        contextLength: 131072,
        minVramGB: 6.0,
        recommended: true
      },
      {
        id: "llama-3.1-8b-Q2_K",
        label: "Q2_K (Ultra Compressed - Low VRAM)",
        quantization: "Q2_K",
        sizeGB: 3.2,
        downloadUrl: "https://huggingface.co/lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q2_K.gguf",
        sha256: "b2c3d4e5f67890123456789012345678901234567890123456789012345678901",
        filename: "Meta-Llama-3.1-8B-Instruct-Q2_K.gguf",
        contextLength: 131072,
        minVramGB: 4.0,
        recommended: false
      }
    ],
    minRequirements: { ramGB: 8, vramGB: 0, diskGB: 7, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 16, vramGB: 8 },
    minComputeScore: 20,
    downloads: 3200000,
    likes: 28000,
    rating: 4.85,
    thumbnailUrl: "",
    createdAt: "2024-07-23T12:00:00Z",
    updatedAt: "2024-07-23T12:00:00Z",
    source: "huggingface",
    hfRepoId: "lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF"
  },
  {
    id: "mistralai/Mistral-7B-Instruct-v0.3-GGUF",
    slug: "mistral-7b-instruct-v0.3",
    name: "Mistral 7B Instruct v0.3",
    author: "Mistral AI",
    category: "chat",
    subcategory: "chat",
    description: "Mistral's best-in-class 7B instruction model with function calling support.",
    longDescription: "Mistral 7B v0.3 is the premier open-source small model for chat, coding, and reasoning tasks. It features sliding window attention, a 32k context window, and native function-calling support.",
    tags: ["gguf", "mistral", "instruction-tuned", "function-calling"],
    license: "apache-2.0",
    requiresAuth: false,
    variants: [
      {
        id: "mistral-7b-v03-Q4_K_M",
        label: "Q4_K_M (Recommended)",
        quantization: "Q4_K_M",
        sizeGB: 4.4,
        downloadUrl: "https://huggingface.co/lmstudio-community/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_M.gguf",
        sha256: "c3d4e5f678901234567890123456789012345678901234567890123456789012",
        filename: "Mistral-7B-Instruct-v0.3-Q4_K_M.gguf",
        contextLength: 32768,
        minVramGB: 5.5,
        recommended: true
      },
      {
        id: "mistral-7b-v03-Q5_K_M",
        label: "Q5_K_M (Higher Quality)",
        quantization: "Q5_K_M",
        sizeGB: 5.1,
        downloadUrl: "https://huggingface.co/lmstudio-community/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q5_K_M.gguf",
        sha256: "d4e5f6789012345678901234567890123456789012345678901234567890123",
        filename: "Mistral-7B-Instruct-v0.3-Q5_K_M.gguf",
        contextLength: 32768,
        minVramGB: 6.5,
        recommended: false
      }
    ],
    minRequirements: { ramGB: 8, vramGB: 0, diskGB: 6, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 16, vramGB: 6 },
    minComputeScore: 18,
    downloads: 2750000,
    likes: 21400,
    rating: 4.82,
    thumbnailUrl: "",
    createdAt: "2024-05-22T12:00:00Z",
    updatedAt: "2024-05-22T12:00:00Z",
    source: "huggingface",
    hfRepoId: "lmstudio-community/Mistral-7B-Instruct-v0.3-GGUF"
  },
  {
    id: "Qwen/Qwen2.5-7B-Instruct-GGUF",
    slug: "qwen-2.5-7b-instruct",
    name: "Qwen 2.5 7B Instruct",
    author: "Alibaba Qwen",
    category: "chat",
    subcategory: "chat",
    description: "Alibaba's powerful general-purpose 7B chat model with 128k context.",
    longDescription: "Qwen 2.5 7B Instruct is a versatile chat model that excels at general-purpose instruction following, multilingual tasks, math reasoning, and code assistance.",
    tags: ["gguf", "qwen2.5", "multilingual", "128k"],
    license: "apache-2.0",
    requiresAuth: false,
    variants: [
      {
        id: "qwen2.5-7b-Q4_K_M",
        label: "Q4_K_M (Recommended)",
        quantization: "Q4_K_M",
        sizeGB: 4.7,
        downloadUrl: "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct-GGUF/resolve/main/qwen2.5-7b-instruct-q4_k_m.gguf",
        sha256: "e5f67890123456789012345678901234567890123456789012345678901234",
        filename: "qwen2.5-7b-instruct-q4_k_m.gguf",
        contextLength: 131072,
        minVramGB: 6.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 8, vramGB: 0, diskGB: 6, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 16, vramGB: 8 },
    minComputeScore: 20,
    downloads: 1870000,
    likes: 15600,
    rating: 4.87,
    thumbnailUrl: "",
    createdAt: "2024-09-18T12:00:00Z",
    updatedAt: "2024-09-18T12:00:00Z",
    source: "huggingface",
    hfRepoId: "Qwen/Qwen2.5-7B-Instruct-GGUF"
  },
  {
    id: "google/gemma-2-2b-it-GGUF",
    slug: "gemma-2-2b-instruct",
    name: "Gemma 2 2B Instruct",
    author: "Google",
    category: "chat",
    subcategory: "chat",
    description: "Google's ultra-compact 2B chat model — perfect for low-power devices.",
    longDescription: "Gemma 2 2B is a lightweight, state-of-the-art open model built from the same research and technology as the Gemini models. It runs efficiently on laptops and even CPUs.",
    tags: ["gguf", "gemma2", "google", "compact"],
    license: "gemma",
    requiresAuth: false,
    variants: [
      {
        id: "gemma2-2b-Q4_K_M",
        label: "Q4_K_M (Recommended)",
        quantization: "Q4_K_M",
        sizeGB: 1.6,
        downloadUrl: "https://huggingface.co/lmstudio-community/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q4_K_M.gguf",
        sha256: "f6789012345678901234567890123456789012345678901234567890123456",
        filename: "gemma-2-2b-it-Q4_K_M.gguf",
        contextLength: 8192,
        minVramGB: 2.5,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 4, vramGB: 0, diskGB: 3, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 8, vramGB: 4 },
    minComputeScore: 5,
    downloads: 920000,
    likes: 9200,
    rating: 4.75,
    thumbnailUrl: "",
    createdAt: "2024-06-27T12:00:00Z",
    updatedAt: "2024-06-27T12:00:00Z",
    source: "huggingface",
    hfRepoId: "lmstudio-community/gemma-2-2b-it-GGUF"
  },
  {
    id: "google/gemma-2-9b-it-GGUF",
    slug: "gemma-2-9b-instruct",
    name: "Gemma 2 9B Instruct",
    author: "Google",
    category: "chat",
    subcategory: "chat",
    description: "Google's mid-range 9B instruction model, punches well above its weight class.",
    longDescription: "Gemma 2 9B offers exceptional performance for its size, rivaling 30B+ models on several benchmarks. It is ideal for complex dialogue, summarization, and multi-step reasoning.",
    tags: ["gguf", "gemma2", "google", "reasoning"],
    license: "gemma",
    requiresAuth: false,
    variants: [
      {
        id: "gemma2-9b-Q4_K_M",
        label: "Q4_K_M (Recommended)",
        quantization: "Q4_K_M",
        sizeGB: 5.5,
        downloadUrl: "https://huggingface.co/lmstudio-community/gemma-2-9b-it-GGUF/resolve/main/gemma-2-9b-it-Q4_K_M.gguf",
        sha256: "67890123456789012345678901234567890123456789012345678901234567",
        filename: "gemma-2-9b-it-Q4_K_M.gguf",
        contextLength: 8192,
        minVramGB: 7.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 16, vramGB: 0, diskGB: 8, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 32, vramGB: 8 },
    minComputeScore: 28,
    downloads: 680000,
    likes: 7400,
    rating: 4.83,
    thumbnailUrl: "",
    createdAt: "2024-06-27T12:00:00Z",
    updatedAt: "2024-06-27T12:00:00Z",
    source: "huggingface",
    hfRepoId: "lmstudio-community/gemma-2-9b-it-GGUF"
  },
  {
    id: "microsoft/Phi-3.5-mini-instruct-GGUF",
    slug: "phi-3.5-mini-instruct",
    name: "Phi-3.5 Mini Instruct",
    author: "Microsoft",
    category: "chat",
    subcategory: "chat",
    description: "Microsoft's incredibly capable 3.8B model — beats 7B models in many benchmarks.",
    longDescription: "Phi-3.5 Mini is a lightweight, state-of-the-art open model built by Microsoft. Despite its small size, it achieves quality close to models 2x its size on reasoning and coding tasks.",
    tags: ["gguf", "phi3", "microsoft", "compact", "reasoning"],
    license: "mit",
    requiresAuth: false,
    variants: [
      {
        id: "phi-3.5-mini-Q4_K_M",
        label: "Q4_K_M (Recommended)",
        quantization: "Q4_K_M",
        sizeGB: 2.4,
        downloadUrl: "https://huggingface.co/lmstudio-community/Phi-3.5-mini-instruct-GGUF/resolve/main/Phi-3.5-mini-instruct-Q4_K_M.gguf",
        sha256: "7890123456789012345678901234567890123456789012345678901234567890",
        filename: "Phi-3.5-mini-instruct-Q4_K_M.gguf",
        contextLength: 128000,
        minVramGB: 3.5,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 4, vramGB: 0, diskGB: 4, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 8, vramGB: 4 },
    minComputeScore: 8,
    downloads: 1100000,
    likes: 11200,
    rating: 4.79,
    thumbnailUrl: "",
    createdAt: "2024-08-20T12:00:00Z",
    updatedAt: "2024-08-20T12:00:00Z",
    source: "huggingface",
    hfRepoId: "lmstudio-community/Phi-3.5-mini-instruct-GGUF"
  },
  {
    id: "microsoft/Phi-4-GGUF",
    slug: "phi-4-14b",
    name: "Phi-4 14B Instruct",
    author: "Microsoft",
    category: "chat",
    subcategory: "reasoning",
    description: "Microsoft's most advanced Phi model — 14B parameters, state-of-the-art reasoning.",
    longDescription: "Phi-4 is Microsoft's top model featuring advanced data curation, synthetic training data, and a post-training regime that emphasizes safety and groundedness. It rivals much larger models.",
    tags: ["gguf", "phi4", "microsoft", "reasoning", "14b"],
    license: "mit",
    requiresAuth: false,
    variants: [
      {
        id: "phi-4-Q4_K_M",
        label: "Q4_K_M (Recommended)",
        quantization: "Q4_K_M",
        sizeGB: 8.5,
        downloadUrl: "https://huggingface.co/lmstudio-community/phi-4-GGUF/resolve/main/phi-4-Q4_K_M.gguf",
        sha256: "890123456789012345678901234567890123456789012345678901234567890",
        filename: "phi-4-Q4_K_M.gguf",
        contextLength: 16384,
        minVramGB: 10.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 16, vramGB: 0, diskGB: 12, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 32, vramGB: 12 },
    minComputeScore: 38,
    downloads: 540000,
    likes: 6800,
    rating: 4.88,
    thumbnailUrl: "",
    createdAt: "2024-12-12T12:00:00Z",
    updatedAt: "2024-12-12T12:00:00Z",
    source: "huggingface",
    hfRepoId: "lmstudio-community/phi-4-GGUF"
  },
  {
    id: "deepseek-ai/DeepSeek-R1-Distill-Llama-8B-GGUF",
    slug: "deepseek-r1-distill-llama-8b",
    name: "DeepSeek R1 Distill Llama 8B",
    author: "DeepSeek",
    category: "chat",
    subcategory: "reasoning",
    description: "DeepSeek's powerful reasoning model distilled into Llama 8B architecture.",
    longDescription: "DeepSeek-R1-Distill-Llama-8B is distilled from the massive DeepSeek-R1 model. It features chain-of-thought reasoning outputs enclosed in `<think>` tags, providing outstanding logic, math, and coding abilities.",
    tags: ["gguf", "reasoning", "distilled", "r1"],
    license: "mit",
    requiresAuth: false,
    variants: [
      {
        id: "deepseek-ai/DeepSeek-R1-Distill-Llama-8B-GGUF-Q4_K_M",
        label: "Q4_K_M (Recommended)",
        quantization: "Q4_K_M",
        sizeGB: 4.9,
        downloadUrl: "https://huggingface.co/unsloth/DeepSeek-R1-Distill-Llama-8B-GGUF/resolve/main/DeepSeek-R1-Distill-Llama-8B-Q4_K_M.gguf",
        sha256: "df488e001cbe651ea652b04f794de750034a3ab8570f7cf7c7c00e12ff488e001",
        filename: "DeepSeek-R1-Distill-Llama-8B-Q4_K_M.gguf",
        contextLength: 8192,
        minVramGB: 6.5,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 16, vramGB: 0, diskGB: 6, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 16, vramGB: 8 },
    minComputeScore: 30,
    downloads: 3500000,
    likes: 42000,
    rating: 4.95,
    thumbnailUrl: "",
    createdAt: "2025-01-20T12:00:00Z",
    updatedAt: "2025-01-20T12:00:00Z",
    source: "huggingface",
    hfRepoId: "unsloth/DeepSeek-R1-Distill-Llama-8B-GGUF"
  },
  {
    id: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B-GGUF",
    slug: "deepseek-r1-distill-qwen-7b",
    name: "DeepSeek R1 Distill Qwen 7B",
    author: "DeepSeek",
    category: "chat",
    subcategory: "reasoning",
    description: "Compact 7B R1 distillate for fast local chain-of-thought reasoning.",
    longDescription: "DeepSeek-R1-Distill-Qwen-7B offers the DeepSeek chain-of-thought reasoning approach in a smaller, faster Qwen 7B architecture. Great for math, science, and coding tasks locally.",
    tags: ["gguf", "reasoning", "distilled", "r1", "qwen"],
    license: "mit",
    requiresAuth: false,
    variants: [
      {
        id: "deepseek-r1-qwen-7b-Q4_K_M",
        label: "Q4_K_M (Recommended)",
        quantization: "Q4_K_M",
        sizeGB: 4.7,
        downloadUrl: "https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-7B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf",
        sha256: "01234567890123456789012345678901234567890123456789012345678901",
        filename: "DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf",
        contextLength: 32768,
        minVramGB: 6.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 8, vramGB: 0, diskGB: 6, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 16, vramGB: 8 },
    minComputeScore: 22,
    downloads: 1900000,
    likes: 23000,
    rating: 4.91,
    thumbnailUrl: "",
    createdAt: "2025-01-20T12:00:00Z",
    updatedAt: "2025-01-20T12:00:00Z",
    source: "huggingface",
    hfRepoId: "unsloth/DeepSeek-R1-Distill-Qwen-7B-GGUF"
  },
  {
    id: "NousResearch/Hermes-3-Llama-3.1-8B-GGUF",
    slug: "hermes-3-llama-3.1-8b",
    name: "Hermes 3 Llama 3.1 8B",
    author: "Nous Research",
    category: "chat",
    subcategory: "agent",
    description: "Top agentic chat model with strong tool calling and system prompt adherence.",
    longDescription: "Hermes 3 is a fine-tuned version of Llama 3.1 8B by Nous Research, specializing in role-playing, agentic behavior, function calling, and long-form creative writing. It excels at structured outputs.",
    tags: ["gguf", "hermes", "agent", "function-calling", "roleplay"],
    license: "llama3.1",
    requiresAuth: false,
    variants: [
      {
        id: "hermes3-llama-3.1-8b-Q4_K_M",
        label: "Q4_K_M (Recommended)",
        quantization: "Q4_K_M",
        sizeGB: 4.9,
        downloadUrl: "https://huggingface.co/NousResearch/Hermes-3-Llama-3.1-8B-GGUF/resolve/main/Hermes-3-Llama-3.1-8B.Q4_K_M.gguf",
        sha256: "12345678901234567890123456789012345678901234567890123456789012",
        filename: "Hermes-3-Llama-3.1-8B.Q4_K_M.gguf",
        contextLength: 131072,
        minVramGB: 6.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 8, vramGB: 0, diskGB: 7, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 16, vramGB: 8 },
    minComputeScore: 22,
    downloads: 760000,
    likes: 8900,
    rating: 4.84,
    thumbnailUrl: "",
    createdAt: "2024-08-12T12:00:00Z",
    updatedAt: "2024-08-12T12:00:00Z",
    source: "huggingface",
    hfRepoId: "NousResearch/Hermes-3-Llama-3.1-8B-GGUF"
  },
  {
    id: "HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF",
    slug: "smollm2-1.7b-instruct",
    name: "SmolLM2 1.7B Instruct",
    author: "HuggingFace",
    category: "chat",
    subcategory: "chat",
    description: "HuggingFace's tiny but capable 1.7B model that runs on any hardware.",
    longDescription: "SmolLM2 is a family of compact language models available in three size: 135M, 360M, and 1.7B parameters. This 1.7B instruct variant is highly capable at basic reasoning and conversation tasks.",
    tags: ["gguf", "smollm", "compact", "cpu-only"],
    license: "apache-2.0",
    requiresAuth: false,
    variants: [
      {
        id: "smollm2-1.7b-Q4_K_M",
        label: "Q4_K_M (Recommended)",
        quantization: "Q4_K_M",
        sizeGB: 1.1,
        downloadUrl: "https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF/resolve/main/smollm2-1.7b-instruct-q4_k_m.gguf",
        sha256: "234567890123456789012345678901234567890123456789012345678901",
        filename: "smollm2-1.7b-instruct-q4_k_m.gguf",
        contextLength: 8192,
        minVramGB: 1.5,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 2, vramGB: 0, diskGB: 2, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 4, vramGB: 2 },
    minComputeScore: 2,
    downloads: 430000,
    likes: 4200,
    rating: 4.62,
    thumbnailUrl: "",
    createdAt: "2024-11-01T12:00:00Z",
    updatedAt: "2024-11-01T12:00:00Z",
    source: "huggingface",
    hfRepoId: "HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF"
  },

  // ─── CODE MODELS ───────────────────────────────────────────────────────────
  {
    id: "Qwen/Qwen2.5-Coder-7B-Instruct-GGUF",
    slug: "qwen-2.5-coder-7b-instruct",
    name: "Qwen 2.5 Coder 7B Instruct",
    author: "Alibaba Qwen",
    category: "code",
    subcategory: "code",
    description: "State-of-the-art 7B code generation and reasoning model from Alibaba.",
    longDescription: "Qwen2.5-Coder-7B-Instruct is a specialized coding model with 128k context support. It ranks highly on coding benchmarks, rivaling much larger models in autocomplete, code repair, and architectural explanation.",
    tags: ["gguf", "coder", "reasoning", "qwen2.5"],
    license: "apache-2.0",
    requiresAuth: false,
    variants: [
      {
        id: "Qwen/Qwen2.5-Coder-7B-Instruct-GGUF-Q4_K_M",
        label: "Q4_K_M (Recommended)",
        quantization: "Q4_K_M",
        sizeGB: 4.7,
        downloadUrl: "https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct-GGUF/resolve/main/Qwen2.5-Coder-7B-Instruct-Q4_K_M.gguf",
        sha256: "cf7c00e12ff488e001cbe651ea652b04f794de750034a3ab8570f7cf7c7c00e1",
        filename: "Qwen2.5-Coder-7B-Instruct-Q4_K_M.gguf",
        contextLength: 131072,
        minVramGB: 6.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 16, vramGB: 0, diskGB: 6, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 16, vramGB: 8 },
    minComputeScore: 25,
    downloads: 980000,
    likes: 8400,
    rating: 4.9,
    createdAt: "2024-11-12T12:00:00Z",
    updatedAt: "2024-11-12T12:00:00Z",
    source: "huggingface",
    hfRepoId: "Qwen/Qwen2.5-Coder-7B-Instruct-GGUF"
  },
  {
    id: "Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF",
    slug: "qwen-2.5-coder-1.5b-instruct",
    name: "Qwen 2.5 Coder 1.5B Instruct",
    author: "Alibaba Qwen",
    category: "code",
    subcategory: "code",
    description: "Lightning-fast 1.5B coding assistant that runs on any laptop.",
    longDescription: "The compact 1.5B version of Qwen 2.5 Coder. Ideal for code completion, syntax correction, and short-form code generation tasks on resource-constrained hardware.",
    tags: ["gguf", "coder", "compact", "qwen2.5", "cpu-friendly"],
    license: "apache-2.0",
    requiresAuth: false,
    variants: [
      {
        id: "qwen2.5-coder-1.5b-Q4_K_M",
        label: "Q4_K_M (Recommended)",
        quantization: "Q4_K_M",
        sizeGB: 1.0,
        downloadUrl: "https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF/resolve/main/qwen2.5-coder-1.5b-instruct-q4_k_m.gguf",
        sha256: "345678901234567890123456789012345678901234567890123456789012",
        filename: "qwen2.5-coder-1.5b-instruct-q4_k_m.gguf",
        contextLength: 131072,
        minVramGB: 1.5,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 4, vramGB: 0, diskGB: 2, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 8, vramGB: 2 },
    minComputeScore: 5,
    downloads: 560000,
    likes: 5100,
    rating: 4.72,
    thumbnailUrl: "",
    createdAt: "2024-11-12T12:00:00Z",
    updatedAt: "2024-11-12T12:00:00Z",
    source: "huggingface",
    hfRepoId: "Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF"
  },
  {
    id: "deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct-GGUF",
    slug: "deepseek-coder-v2-lite",
    name: "DeepSeek Coder V2 Lite Instruct",
    author: "DeepSeek",
    category: "code",
    subcategory: "code",
    description: "Powerful 16B MoE coding model from DeepSeek with 128k context.",
    longDescription: "DeepSeek-Coder-V2-Lite is a Mixture-of-Experts coding model that supports 338 programming languages. At 16B parameters with MoE efficiency, it matches GPT-4 Turbo on HumanEval.",
    tags: ["gguf", "coder", "moe", "deepseek", "128k"],
    license: "deepseek",
    requiresAuth: false,
    variants: [
      {
        id: "deepseek-coder-v2-lite-Q4_K_M",
        label: "Q4_K_M (Recommended)",
        quantization: "Q4_K_M",
        sizeGB: 9.7,
        downloadUrl: "https://huggingface.co/lmstudio-community/DeepSeek-Coder-V2-Lite-Instruct-GGUF/resolve/main/DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf",
        sha256: "456789012345678901234567890123456789012345678901234567890123",
        filename: "DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf",
        contextLength: 131072,
        minVramGB: 12.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 16, vramGB: 0, diskGB: 12, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 32, vramGB: 16 },
    minComputeScore: 40,
    downloads: 720000,
    likes: 8100,
    rating: 4.88,
    thumbnailUrl: "",
    createdAt: "2024-06-17T12:00:00Z",
    updatedAt: "2024-06-17T12:00:00Z",
    source: "huggingface",
    hfRepoId: "lmstudio-community/DeepSeek-Coder-V2-Lite-Instruct-GGUF"
  },
  {
    id: "microsoft/phi-3-medium-4k-instruct-GGUF",
    slug: "phi-3-medium-4k-instruct",
    name: "Phi-3 Medium 4K Instruct",
    author: "Microsoft",
    category: "code",
    subcategory: "code",
    description: "Microsoft's 14B coding + reasoning model for advanced code generation.",
    longDescription: "Phi-3 Medium is a 14B parameter model from Microsoft, fine-tuned for coding tasks with strong benchmarks on HumanEval, MBPP, and Math. It supports a 4k context window.",
    tags: ["gguf", "phi3", "microsoft", "14b", "coding"],
    license: "mit",
    requiresAuth: false,
    variants: [
      {
        id: "phi3-medium-4k-Q4_K_M",
        label: "Q4_K_M (Recommended)",
        quantization: "Q4_K_M",
        sizeGB: 8.4,
        downloadUrl: "https://huggingface.co/lmstudio-community/Phi-3-medium-4k-instruct-GGUF/resolve/main/Phi-3-medium-4k-instruct-Q4_K_M.gguf",
        sha256: "56789012345678901234567890123456789012345678901234567890123456",
        filename: "Phi-3-medium-4k-instruct-Q4_K_M.gguf",
        contextLength: 4096,
        minVramGB: 10.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 16, vramGB: 0, diskGB: 12, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 32, vramGB: 12 },
    minComputeScore: 38,
    downloads: 390000,
    likes: 4500,
    rating: 4.79,
    thumbnailUrl: "",
    createdAt: "2024-04-23T12:00:00Z",
    updatedAt: "2024-04-23T12:00:00Z",
    source: "huggingface",
    hfRepoId: "lmstudio-community/Phi-3-medium-4k-instruct-GGUF"
  },

  // ─── IMAGE GENERATION ──────────────────────────────────────────────────────
  {
    id: "black-forest-labs/FLUX.1-schnell",
    slug: "flux-schnell",
    name: "FLUX.1 Schnell",
    author: "Black Forest Labs",
    category: "image-gen",
    subcategory: "image",
    description: "SOTA 12B parameter image generator optimized for fast 4-step generation.",
    longDescription: "FLUX.1 Schnell is a cutting-edge text-to-image model by the creators of Stable Diffusion. It produces exceptional details, high text adherence, and realistic hands in just 4 generation steps.",
    tags: ["safetensors", "flux", "schnell", "diffusion"],
    license: "apache-2.0",
    requiresAuth: false,
    variants: [
      {
        id: "flux-schnell-fp8",
        label: "FP8 (Recommended - 8-bit Quantized)",
        quantization: "FP8",
        sizeGB: 11.8,
        downloadUrl: "https://huggingface.co/black-forest-labs/FLUX.1-schnell/resolve/main/flux1-schnell.safetensors",
        sha256: "ea652b04f794de750034a3ab8570f7cf7c7c00e12ff488e001cbe651ea652b04f",
        filename: "flux1-schnell.safetensors",
        minVramGB: 12.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 16, vramGB: 12, diskGB: 15, backend: ["cuda", "metal"] },
    recommendedRequirements: { ramGB: 32, vramGB: 16 },
    minComputeScore: 60,
    downloads: 2300000,
    likes: 19800,
    rating: 4.9,
    thumbnailUrl: "",
    createdAt: "2024-08-01T12:00:00Z",
    updatedAt: "2024-08-01T12:00:00Z",
    source: "huggingface",
    hfRepoId: "black-forest-labs/FLUX.1-schnell"
  },
  {
    id: "stabilityai/stable-diffusion-xl-base-1.0",
    slug: "sdxl-base-1.0",
    name: "Stable Diffusion XL 1.0",
    author: "Stability AI",
    category: "image-gen",
    subcategory: "image",
    description: "The original SDXL — high-fidelity 1024px image generation with a massive community ecosystem.",
    longDescription: "SDXL is the flagship Stable Diffusion model from Stability AI. It generates 1024x1024 images with excellent prompt adherence and photorealism, and has the largest library of community fine-tunes and LoRAs.",
    tags: ["safetensors", "sdxl", "stable-diffusion", "diffusion"],
    license: "openrail++",
    requiresAuth: false,
    variants: [
      {
        id: "sdxl-base-1.0-fp16",
        label: "FP16 (Recommended)",
        quantization: "FP16",
        sizeGB: 6.6,
        downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors",
        sha256: "6789012345678901234567890123456789012345678901234567890123456789",
        filename: "sd_xl_base_1.0.safetensors",
        minVramGB: 8.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 8, vramGB: 8, diskGB: 10, backend: ["cuda", "metal"] },
    recommendedRequirements: { ramGB: 16, vramGB: 12 },
    minComputeScore: 50,
    downloads: 5600000,
    likes: 45000,
    rating: 4.85,
    thumbnailUrl: "",
    createdAt: "2023-07-26T12:00:00Z",
    updatedAt: "2023-07-26T12:00:00Z",
    source: "huggingface",
    hfRepoId: "stabilityai/stable-diffusion-xl-base-1.0"
  },
  {
    id: "stabilityai/stable-diffusion-2-1",
    slug: "stable-diffusion-2-1",
    name: "Stable Diffusion 2.1",
    author: "Stability AI",
    category: "image-gen",
    subcategory: "image",
    description: "SD 2.1 — the classic high-quality 768px image model with lower VRAM requirements.",
    longDescription: "Stable Diffusion 2.1 is a well-established text-to-image model producing 768x768 images. It works on most modern GPUs and is widely supported across inference engines.",
    tags: ["safetensors", "stable-diffusion", "sd2", "diffusion"],
    license: "openrail++",
    requiresAuth: false,
    variants: [
      {
        id: "sd-2.1-fp16",
        label: "FP16 (Recommended)",
        quantization: "FP16",
        sizeGB: 5.2,
        downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-2-1/resolve/main/v2-1_768-ema-pruned.safetensors",
        sha256: "789012345678901234567890123456789012345678901234567890123456789",
        filename: "v2-1_768-ema-pruned.safetensors",
        minVramGB: 6.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 8, vramGB: 6, diskGB: 8, backend: ["cuda", "metal"] },
    recommendedRequirements: { ramGB: 16, vramGB: 8 },
    minComputeScore: 45,
    downloads: 8100000,
    likes: 62000,
    rating: 4.78,
    thumbnailUrl: "",
    createdAt: "2022-12-07T12:00:00Z",
    updatedAt: "2022-12-07T12:00:00Z",
    source: "huggingface",
    hfRepoId: "stabilityai/stable-diffusion-2-1"
  },
  {
    id: "runwayml/stable-diffusion-v1-5",
    slug: "stable-diffusion-1-5",
    name: "Stable Diffusion 1.5",
    author: "RunwayML",
    category: "image-gen",
    subcategory: "image",
    description: "The classic SD 1.5 — lowest VRAM, massive LoRA ecosystem, great for beginners.",
    longDescription: "Stable Diffusion 1.5 remains widely used due to its massive community ecosystem of fine-tunes, LoRAs, and textual inversions. It runs on as little as 4GB VRAM making it highly accessible.",
    tags: ["safetensors", "stable-diffusion", "sd1.5", "diffusion", "lora"],
    license: "openrail",
    requiresAuth: false,
    variants: [
      {
        id: "sd-1.5-fp16",
        label: "FP16 (Recommended)",
        quantization: "FP16",
        sizeGB: 4.2,
        downloadUrl: "https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors",
        sha256: "89012345678901234567890123456789012345678901234567890123456789",
        filename: "v1-5-pruned-emaonly.safetensors",
        minVramGB: 4.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 8, vramGB: 4, diskGB: 6, backend: ["cuda", "metal"] },
    recommendedRequirements: { ramGB: 16, vramGB: 6 },
    minComputeScore: 35,
    downloads: 15000000,
    likes: 98000,
    rating: 4.72,
    thumbnailUrl: "",
    createdAt: "2022-10-20T12:00:00Z",
    updatedAt: "2022-10-20T12:00:00Z",
    source: "huggingface",
    hfRepoId: "runwayml/stable-diffusion-v1-5"
  },
  {
    id: "PixArt-alpha/PixArt-Sigma-XL-2-1024-MS",
    slug: "pixart-sigma-xl",
    name: "PixArt Sigma XL",
    author: "PixArt-alpha",
    category: "image-gen",
    subcategory: "image",
    description: "High-quality diffusion model with exceptional typography and photorealism.",
    longDescription: "PixArt Sigma offers state-of-the-art image generation with particularly impressive text rendering within images, photorealistic lighting, and excellent composition at 1024px.",
    tags: ["safetensors", "pixart", "sigma", "diffusion", "typography"],
    license: "openrail++",
    requiresAuth: false,
    variants: [
      {
        id: "pixart-sigma-xl-fp16",
        label: "FP16 (Recommended)",
        quantization: "FP16",
        sizeGB: 8.2,
        downloadUrl: "https://huggingface.co/PixArt-alpha/PixArt-Sigma-XL-2-1024-MS/resolve/main/PixArt-Sigma-XL-2-1024-MS.safetensors",
        sha256: "9012345678901234567890123456789012345678901234567890123456789",
        filename: "PixArt-Sigma-XL-2-1024-MS.safetensors",
        minVramGB: 10.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 16, vramGB: 10, diskGB: 12, backend: ["cuda", "metal"] },
    recommendedRequirements: { ramGB: 32, vramGB: 16 },
    minComputeScore: 55,
    downloads: 380000,
    likes: 5200,
    rating: 4.82,
    thumbnailUrl: "",
    createdAt: "2024-04-15T12:00:00Z",
    updatedAt: "2024-04-15T12:00:00Z",
    source: "huggingface",
    hfRepoId: "PixArt-alpha/PixArt-Sigma-XL-2-1024-MS"
  },

  // ─── AUDIO GENERATION ──────────────────────────────────────────────────────
  {
    id: "facebook/musicgen-small",
    slug: "musicgen-small",
    name: "MusicGen Small",
    author: "Meta AI",
    category: "audio-gen",
    subcategory: "music",
    description: "Controllable music generation model trained on licensed music, optimized for offline loop synthesis.",
    longDescription: "MusicGen is a single-stage auto-regressive Transformer model trained by Meta AI for generating high-quality music samples conditioned on text descriptions or audio prompts.",
    tags: ["safetensors", "musicgen", "audio-gen", "music"],
    license: "cc-by-nc-4.0",
    requiresAuth: false,
    variants: [
      {
        id: "musicgen-small-fp16",
        label: "FP16 (Recommended)",
        quantization: "FP16",
        sizeGB: 0.6,
        downloadUrl: "https://huggingface.co/facebook/musicgen-small/resolve/main/state_dict.bin",
        sha256: "cf7c00e12ff488e001cbe651ea652b04f794de750034a3ab8570f7cf7c7c00e1",
        filename: "musicgen_small.bin",
        minVramGB: 0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 8, vramGB: 0, diskGB: 2, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 16, vramGB: 4 },
    minComputeScore: 20,
    downloads: 850000,
    likes: 6400,
    rating: 4.8,
    thumbnailUrl: "",
    createdAt: "2023-06-01T12:00:00Z",
    updatedAt: "2023-06-01T12:00:00Z",
    source: "huggingface",
    hfRepoId: "facebook/musicgen-small"
  },
  {
    id: "facebook/musicgen-medium",
    slug: "musicgen-medium",
    name: "MusicGen Medium",
    author: "Meta AI",
    category: "audio-gen",
    subcategory: "music",
    description: "Higher quality 1.5B parameter music generation model.",
    longDescription: "MusicGen Medium has 1.5B parameters and produces higher quality, more musically coherent audio tracks compared to the Small variant. Requires moderate GPU memory.",
    tags: ["safetensors", "musicgen", "audio-gen", "music", "1.5b"],
    license: "cc-by-nc-4.0",
    requiresAuth: false,
    variants: [
      {
        id: "musicgen-medium-fp16",
        label: "FP16 (Recommended)",
        quantization: "FP16",
        sizeGB: 3.1,
        downloadUrl: "https://huggingface.co/facebook/musicgen-medium/resolve/main/state_dict.bin",
        sha256: "012345678901234567890123456789012345678901234567890123456789012",
        filename: "musicgen_medium.bin",
        minVramGB: 4.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 8, vramGB: 0, diskGB: 4, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 16, vramGB: 6 },
    minComputeScore: 28,
    downloads: 490000,
    likes: 4800,
    rating: 4.82,
    thumbnailUrl: "",
    createdAt: "2023-06-01T12:00:00Z",
    updatedAt: "2023-06-01T12:00:00Z",
    source: "huggingface",
    hfRepoId: "facebook/musicgen-medium"
  },
  {
    id: "stability-ai/stable-audio-open-1.0",
    slug: "stable-audio-open-1.0",
    name: "Stable Audio Open 1.0",
    author: "Stability AI",
    category: "audio-gen",
    subcategory: "sfx",
    description: "Open-weight model for generating variable-length stereo audio from text prompts.",
    longDescription: "Stable Audio Open generates up to 47 seconds of high-quality audio at 44.1kHz from text prompts. It excels at generating sound effects, samples, and production-ready stems.",
    tags: ["safetensors", "audio-gen", "stable-audio", "sfx", "stereo"],
    license: "stability-ai-open-rail-m",
    requiresAuth: false,
    variants: [
      {
        id: "stable-audio-open-1.0-fp16",
        label: "FP16 (Recommended)",
        quantization: "FP16",
        sizeGB: 2.8,
        downloadUrl: "https://huggingface.co/stabilityai/stable-audio-open-1.0/resolve/main/model.safetensors",
        sha256: "1234567890123456789012345678901234567890123456789012345678901",
        filename: "stable_audio_open_1.0.safetensors",
        minVramGB: 4.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 8, vramGB: 0, diskGB: 5, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 16, vramGB: 8 },
    minComputeScore: 22,
    downloads: 320000,
    likes: 3800,
    rating: 4.76,
    thumbnailUrl: "",
    createdAt: "2024-07-09T12:00:00Z",
    updatedAt: "2024-07-09T12:00:00Z",
    source: "huggingface",
    hfRepoId: "stabilityai/stable-audio-open-1.0"
  },

  // ─── VIDEO GENERATION ──────────────────────────────────────────────────────
  {
    id: "THUDM/CogVideoX-2b",
    slug: "cogvideox-2b",
    name: "CogVideoX 2B",
    author: "THUDM",
    category: "video-gen",
    subcategory: "t2v",
    description: "Compact 2B text-to-video model from Tsinghua — runs on consumer GPUs.",
    longDescription: "CogVideoX-2B is a diffusion transformer for text-to-video generation. It can produce 6-second videos at 720x480 resolution, runs on 8GB VRAM, and delivers cinematic motion quality.",
    tags: ["safetensors", "cogvideox", "t2v", "video-gen", "diffusion"],
    license: "apache-2.0",
    requiresAuth: false,
    variants: [
      {
        id: "cogvideox-2b-fp16",
        label: "BF16 (Recommended)",
        quantization: "BF16",
        sizeGB: 5.0,
        downloadUrl: "https://huggingface.co/THUDM/CogVideoX-2b/resolve/main/transformer/diffusion_pytorch_model.safetensors",
        sha256: "2345678901234567890123456789012345678901234567890123456789012",
        filename: "cogvideox_2b_bf16.safetensors",
        minVramGB: 8.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 16, vramGB: 8, diskGB: 10, backend: ["cuda", "metal"] },
    recommendedRequirements: { ramGB: 32, vramGB: 16 },
    minComputeScore: 52,
    downloads: 420000,
    likes: 6200,
    rating: 4.78,
    thumbnailUrl: "",
    createdAt: "2024-08-06T12:00:00Z",
    updatedAt: "2024-08-06T12:00:00Z",
    source: "huggingface",
    hfRepoId: "THUDM/CogVideoX-2b"
  },
  {
    id: "guoyww/animatediff-motion-adapter-v1-5-2",
    slug: "animatediff-v1.5-2",
    name: "AnimateDiff Motion Adapter v1.5.2",
    author: "guoyww",
    category: "video-gen",
    subcategory: "img2v",
    description: "Turn any SD 1.5 model into a video generator with this motion adapter.",
    longDescription: "AnimateDiff is a motion module that can be plugged into existing Stable Diffusion 1.5 checkpoints to animate static images. It generates smooth 16-frame video clips from text prompts.",
    tags: ["safetensors", "animatediff", "motion-adapter", "sd1.5", "video"],
    license: "openrail++",
    requiresAuth: false,
    variants: [
      {
        id: "animatediff-v1.5.2-fp16",
        label: "FP16 (Recommended)",
        quantization: "FP16",
        sizeGB: 1.8,
        downloadUrl: "https://huggingface.co/guoyww/animatediff/resolve/main/mm_sd_v15_v2.ckpt",
        sha256: "3456789012345678901234567890123456789012345678901234567890123",
        filename: "mm_sd_v15_v2.ckpt",
        minVramGB: 6.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 8, vramGB: 6, diskGB: 5, backend: ["cuda", "metal"] },
    recommendedRequirements: { ramGB: 16, vramGB: 8 },
    minComputeScore: 45,
    downloads: 680000,
    likes: 8800,
    rating: 4.73,
    thumbnailUrl: "",
    createdAt: "2023-07-14T12:00:00Z",
    updatedAt: "2023-07-14T12:00:00Z",
    source: "huggingface",
    hfRepoId: "guoyww/animatediff"
  },
  {
    id: "genmo/mochi-1-preview",
    slug: "mochi-1-preview",
    name: "Mochi 1 Preview",
    author: "Genmo",
    category: "video-gen",
    subcategory: "t2v",
    description: "High-fidelity open-weight video generation model with fluid motion.",
    longDescription: "Mochi 1 is an open-source state-of-the-art video generation model from Genmo. It features 10B parameters, exceptional motion quality, and high coherence between text and video.",
    tags: ["safetensors", "mochi", "video-gen", "t2v", "10b"],
    license: "apache-2.0",
    requiresAuth: false,
    variants: [
      {
        id: "mochi-1-bf16",
        label: "BF16 (Recommended)",
        quantization: "BF16",
        sizeGB: 20.0,
        downloadUrl: "https://huggingface.co/genmo/mochi-1-preview/resolve/main/dit.safetensors",
        sha256: "456789012345678901234567890123456789012345678901234567890123456",
        filename: "mochi1_dit_bf16.safetensors",
        minVramGB: 24.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 32, vramGB: 24, diskGB: 25, backend: ["cuda"] },
    recommendedRequirements: { ramGB: 64, vramGB: 40 },
    minComputeScore: 80,
    downloads: 180000,
    likes: 4400,
    rating: 4.81,
    thumbnailUrl: "",
    createdAt: "2024-10-22T12:00:00Z",
    updatedAt: "2024-10-22T12:00:00Z",
    source: "huggingface",
    hfRepoId: "genmo/mochi-1-preview"
  },

  // ─── TEXT-TO-SPEECH ────────────────────────────────────────────────────────
  {
    id: "hexgrad/Kokoro-82M",
    slug: "kokoro-tts",
    name: "Kokoro 82M",
    author: "Hexgrad",
    category: "tts",
    subcategory: "audio",
    description: "Ultralight, high-quality text-to-speech model running completely client-side.",
    longDescription: "Kokoro is a highly efficient 82M parameter TTS model. It delivers expressiveness and clarity rivaling cloud TTS services while occupying minimal memory and disk footprint.",
    tags: ["onnx", "tts", "speech", "kokoro"],
    license: "apache-2.0",
    requiresAuth: false,
    variants: [
      {
        id: "kokoro-82m-onnx",
        label: "ONNX (Recommended)",
        quantization: "FP32",
        sizeGB: 0.34,
        downloadUrl: "https://huggingface.co/hexgrad/Kokoro-82M/resolve/main/kokoro-v0_19.onnx",
        sha256: "b04f794de750034a3ab8570f7cf7c7c00e12ff488e001cbe651ea652b04fa794",
        filename: "kokoro-v0_19.onnx",
        minVramGB: 0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 4, vramGB: 0, diskGB: 1, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 8, vramGB: 2 },
    minComputeScore: 5,
    downloads: 450000,
    likes: 5400,
    rating: 4.85,
    thumbnailUrl: "",
    createdAt: "2024-12-20T12:00:00Z",
    updatedAt: "2024-12-20T12:00:00Z",
    source: "huggingface",
    hfRepoId: "hexgrad/Kokoro-82M"
  },
  {
    id: "coqui/XTTS-v2",
    slug: "xtts-v2",
    name: "XTTS v2",
    author: "Coqui AI",
    category: "tts",
    subcategory: "audio",
    description: "Zero-shot voice cloning TTS — clone any voice from a 6-second sample.",
    longDescription: "XTTS v2 supports zero-shot voice cloning in 17 languages from a short audio reference. It produces natural-sounding speech with the target speaker's voice characteristics.",
    tags: ["bin", "tts", "voice-cloning", "multilingual", "xtts"],
    license: "coqui-public-model-license",
    requiresAuth: false,
    variants: [
      {
        id: "xtts-v2-fp16",
        label: "FP16 (Recommended)",
        quantization: "FP16",
        sizeGB: 1.9,
        downloadUrl: "https://huggingface.co/coqui/XTTS-v2/resolve/main/model.pth",
        sha256: "567890123456789012345678901234567890123456789012345678901234",
        filename: "xtts_v2.pth",
        minVramGB: 0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 4, vramGB: 0, diskGB: 3, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 8, vramGB: 4 },
    minComputeScore: 12,
    downloads: 890000,
    likes: 9800,
    rating: 4.88,
    thumbnailUrl: "",
    createdAt: "2023-12-14T12:00:00Z",
    updatedAt: "2023-12-14T12:00:00Z",
    source: "huggingface",
    hfRepoId: "coqui/XTTS-v2"
  },
  {
    id: "metavoiceio/metavoice-1B-v0.1",
    slug: "metavoice-1b",
    name: "MetaVoice 1B",
    author: "MetaVoice",
    category: "tts",
    subcategory: "audio",
    description: "1B parameter TTS model for natural-sounding American English speech.",
    longDescription: "MetaVoice-1B is a 1.2 billion parameter text-to-speech model trained on 100k hours of speech data. It produces highly natural prosody and intonation for English text.",
    tags: ["bin", "tts", "speech", "1b", "english"],
    license: "apache-2.0",
    requiresAuth: false,
    variants: [
      {
        id: "metavoice-1b-fp16",
        label: "FP16 (Recommended)",
        quantization: "FP16",
        sizeGB: 2.3,
        downloadUrl: "https://huggingface.co/metavoiceio/metavoice-1B-v0.1/resolve/main/weights.pt",
        sha256: "678901234567890123456789012345678901234567890123456789012345",
        filename: "metavoice_1b_weights.pt",
        minVramGB: 0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 8, vramGB: 0, diskGB: 4, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 16, vramGB: 4 },
    minComputeScore: 15,
    downloads: 210000,
    likes: 2900,
    rating: 4.71,
    thumbnailUrl: "",
    createdAt: "2024-02-06T12:00:00Z",
    updatedAt: "2024-02-06T12:00:00Z",
    source: "huggingface",
    hfRepoId: "metavoiceio/metavoice-1B-v0.1"
  },

  // ─── SPEECH-TO-TEXT ────────────────────────────────────────────────────────
  {
    id: "openai/whisper-base",
    slug: "whisper-base",
    name: "Whisper Base",
    author: "OpenAI",
    category: "stt",
    subcategory: "transcribe",
    description: "Efficient multi-lingual automatic speech recognition and translation model.",
    longDescription: "Whisper Base is a 74M parameter model trained by OpenAI for high-performance offline speech transcription. It supports automatic language identification and English translation capabilities.",
    tags: ["bin", "whisper.cpp", "stt", "transcription"],
    license: "mit",
    requiresAuth: false,
    variants: [
      {
        id: "whisper-base-ggml",
        label: "GGML Format (Recommended)",
        quantization: "FP16",
        sizeGB: 0.15,
        downloadUrl: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin",
        sha256: "001cbe651ea652b04f794de750034a3ab8570f7cf7c7c00e12ff488e001cbe65",
        filename: "ggml-base.bin",
        minVramGB: 0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 4, vramGB: 0, diskGB: 1, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 8, vramGB: 2 },
    minComputeScore: 5,
    downloads: 1200000,
    likes: 7200,
    rating: 4.7,
    thumbnailUrl: "",
    createdAt: "2022-12-01T12:00:00Z",
    updatedAt: "2023-05-01T12:00:00Z",
    source: "huggingface",
    hfRepoId: "ggerganov/whisper.cpp"
  },
  {
    id: "openai/whisper-small",
    slug: "whisper-small",
    name: "Whisper Small",
    author: "OpenAI",
    category: "stt",
    subcategory: "transcribe",
    description: "Small Whisper model — 244M params, better accuracy than Base, still very fast.",
    longDescription: "Whisper Small is a 244M parameter multilingual ASR model that provides a great balance of accuracy and speed. It supports 99 languages and English translation.",
    tags: ["bin", "whisper.cpp", "stt", "transcription", "multilingual"],
    license: "mit",
    requiresAuth: false,
    variants: [
      {
        id: "whisper-small-ggml",
        label: "GGML Format (Recommended)",
        quantization: "FP16",
        sizeGB: 0.47,
        downloadUrl: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.bin",
        sha256: "11cbe651ea652b04f794de750034a3ab8570f7cf7c7c00e12ff488e001cbe65",
        filename: "ggml-small.bin",
        minVramGB: 0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 4, vramGB: 0, diskGB: 1, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 8, vramGB: 2 },
    minComputeScore: 8,
    downloads: 870000,
    likes: 5600,
    rating: 4.75,
    thumbnailUrl: "",
    createdAt: "2022-12-01T12:00:00Z",
    updatedAt: "2023-05-01T12:00:00Z",
    source: "huggingface",
    hfRepoId: "ggerganov/whisper.cpp"
  },
  {
    id: "openai/whisper-medium",
    slug: "whisper-medium",
    name: "Whisper Medium",
    author: "OpenAI",
    category: "stt",
    subcategory: "transcribe",
    description: "769M param Whisper Medium — near-perfect transcription for 99 languages.",
    longDescription: "Whisper Medium is a 769M parameter model delivering excellent transcription accuracy across 99 languages. It is the recommended choice for professional-quality offline transcription.",
    tags: ["bin", "whisper.cpp", "stt", "transcription", "professional"],
    license: "mit",
    requiresAuth: false,
    variants: [
      {
        id: "whisper-medium-ggml",
        label: "GGML Format (Recommended)",
        quantization: "FP16",
        sizeGB: 1.5,
        downloadUrl: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-medium.bin",
        sha256: "22cbe651ea652b04f794de750034a3ab8570f7cf7c7c00e12ff488e001cbe65",
        filename: "ggml-medium.bin",
        minVramGB: 0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 4, vramGB: 0, diskGB: 3, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 8, vramGB: 4 },
    minComputeScore: 12,
    downloads: 640000,
    likes: 4800,
    rating: 4.82,
    thumbnailUrl: "",
    createdAt: "2022-12-01T12:00:00Z",
    updatedAt: "2023-05-01T12:00:00Z",
    source: "huggingface",
    hfRepoId: "ggerganov/whisper.cpp"
  },
  {
    id: "openai/whisper-large-v3",
    slug: "whisper-large-v3",
    name: "Whisper Large v3",
    author: "OpenAI",
    category: "stt",
    subcategory: "transcribe",
    description: "The most accurate Whisper model — 1.5B params, 99-language coverage.",
    longDescription: "Whisper Large v3 is the top model in the Whisper family with 1550M parameters. It achieves the lowest word error rate across virtually all languages and accents.",
    tags: ["bin", "whisper.cpp", "stt", "transcription", "large", "best-accuracy"],
    license: "mit",
    requiresAuth: false,
    variants: [
      {
        id: "whisper-large-v3-ggml",
        label: "GGML Format (Recommended)",
        quantization: "FP16",
        sizeGB: 3.1,
        downloadUrl: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3.bin",
        sha256: "33cbe651ea652b04f794de750034a3ab8570f7cf7c7c00e12ff488e001cbe65",
        filename: "ggml-large-v3.bin",
        minVramGB: 4.0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 8, vramGB: 0, diskGB: 5, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 16, vramGB: 6 },
    minComputeScore: 20,
    downloads: 920000,
    likes: 8900,
    rating: 4.93,
    thumbnailUrl: "",
    createdAt: "2023-11-06T12:00:00Z",
    updatedAt: "2023-11-06T12:00:00Z",
    source: "huggingface",
    hfRepoId: "ggerganov/whisper.cpp"
  },
  {
    id: "distil-whisper/distil-large-v3-GGUF",
    slug: "distil-whisper-large-v3",
    name: "Distil-Whisper Large v3",
    author: "HuggingFace",
    category: "stt",
    subcategory: "transcribe",
    description: "6x faster, 49% smaller Whisper Large v3 distillate — English only.",
    longDescription: "Distil-Whisper is a distilled version of Whisper Large v3 that is 6 times faster and 49% smaller while retaining 98.7% of the accuracy for English speech recognition.",
    tags: ["bin", "whisper.cpp", "stt", "distilled", "fast", "english"],
    license: "mit",
    requiresAuth: false,
    variants: [
      {
        id: "distil-whisper-large-v3-q5_0",
        label: "Q5_0 (Recommended - Fast)",
        quantization: "Q5_0",
        sizeGB: 1.4,
        downloadUrl: "https://huggingface.co/distil-whisper/distil-large-v3-gguf/resolve/main/ggml-distil-large-v3.bin",
        sha256: "44cbe651ea652b04f794de750034a3ab8570f7cf7c7c00e12ff488e001cbe65",
        filename: "ggml-distil-large-v3.bin",
        minVramGB: 0,
        recommended: true
      }
    ],
    minRequirements: { ramGB: 4, vramGB: 0, diskGB: 3, backend: ["cpu", "metal", "cuda"] },
    recommendedRequirements: { ramGB: 8, vramGB: 2 },
    minComputeScore: 10,
    downloads: 580000,
    likes: 6200,
    rating: 4.89,
    thumbnailUrl: "",
    createdAt: "2024-02-01T12:00:00Z",
    updatedAt: "2024-02-01T12:00:00Z",
    source: "huggingface",
    hfRepoId: "distil-whisper/distil-large-v3-gguf"
  }
];
