/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InstalledRouteImport } from './routes/installed'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BenchmarkRouteImport } from './routes/benchmark'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HubIndexRouteImport } from './routes/hub/index'
import { Route as PlaygroundVideoRouteImport } from './routes/playground/video'
import { Route as PlaygroundTtsRouteImport } from './routes/playground/tts'
import { Route as PlaygroundSttRouteImport } from './routes/playground/stt'
import { Route as PlaygroundImageRouteImport } from './routes/playground/image'
import { Route as PlaygroundChatRouteImport } from './routes/playground/chat'
import { Route as PlaygroundAudioRouteImport } from './routes/playground/audio'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalledRoute = InstalledRouteImport.update({
  id: '/installed',
  path: '/installed',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkRoute = BenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundVideoRoute = PlaygroundVideoRouteImport.update({
  id: '/playground/video',
  path: '/playground/video',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundTtsRoute = PlaygroundTtsRouteImport.update({
  id: '/playground/tts',
  path: '/playground/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundSttRoute = PlaygroundSttRouteImport.update({
  id: '/playground/stt',
  path: '/playground/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundImageRoute = PlaygroundImageRouteImport.update({
  id: '/playground/image',
  path: '/playground/image',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundChatRoute = PlaygroundChatRouteImport.update({
  id: '/playground/chat',
  path: '/playground/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundAudioRoute = PlaygroundAudioRouteImport.update({
  id: '/playground/audio',
  path: '/playground/audio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/compare': typeof CompareRoute
  '/downloads': typeof DownloadsRoute
  '/installed': typeof InstalledRoute
  '/settings': typeof SettingsRoute
  '/playground/audio': typeof PlaygroundAudioRoute
  '/playground/chat': typeof PlaygroundChatRoute
  '/playground/image': typeof PlaygroundImageRoute
  '/playground/stt': typeof PlaygroundSttRoute
  '/playground/tts': typeof PlaygroundTtsRoute
  '/playground/video': typeof PlaygroundVideoRoute
  '/hub/': typeof HubIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/compare': typeof CompareRoute
  '/downloads': typeof DownloadsRoute
  '/installed': typeof InstalledRoute
  '/settings': typeof SettingsRoute
  '/playground/audio': typeof PlaygroundAudioRoute
  '/playground/chat': typeof PlaygroundChatRoute
  '/playground/image': typeof PlaygroundImageRoute
  '/playground/stt': typeof PlaygroundSttRoute
  '/playground/tts': typeof PlaygroundTtsRoute
  '/playground/video': typeof PlaygroundVideoRoute
  '/hub': typeof HubIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/compare': typeof CompareRoute
  '/downloads': typeof DownloadsRoute
  '/installed': typeof InstalledRoute
  '/settings': typeof SettingsRoute
  '/playground/audio': typeof PlaygroundAudioRoute
  '/playground/chat': typeof PlaygroundChatRoute
  '/playground/image': typeof PlaygroundImageRoute
  '/playground/stt': typeof PlaygroundSttRoute
  '/playground/tts': typeof PlaygroundTtsRoute
  '/playground/video': typeof PlaygroundVideoRoute
  '/hub/': typeof HubIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benchmark'
    | '/compare'
    | '/downloads'
    | '/installed'
    | '/settings'
    | '/playground/audio'
    | '/playground/chat'
    | '/playground/image'
    | '/playground/stt'
    | '/playground/tts'
    | '/playground/video'
    | '/hub/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/benchmark'
    | '/compare'
    | '/downloads'
    | '/installed'
    | '/settings'
    | '/playground/audio'
    | '/playground/chat'
    | '/playground/image'
    | '/playground/stt'
    | '/playground/tts'
    | '/playground/video'
    | '/hub'
  id:
    | '__root__'
    | '/'
    | '/benchmark'
    | '/compare'
    | '/downloads'
    | '/installed'
    | '/settings'
    | '/playground/audio'
    | '/playground/chat'
    | '/playground/image'
    | '/playground/stt'
    | '/playground/tts'
    | '/playground/video'
    | '/hub/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchmarkRoute: typeof BenchmarkRoute
  CompareRoute: typeof CompareRoute
  DownloadsRoute: typeof DownloadsRoute
  InstalledRoute: typeof InstalledRoute
  SettingsRoute: typeof SettingsRoute
  PlaygroundAudioRoute: typeof PlaygroundAudioRoute
  PlaygroundChatRoute: typeof PlaygroundChatRoute
  PlaygroundImageRoute: typeof PlaygroundImageRoute
  PlaygroundSttRoute: typeof PlaygroundSttRoute
  PlaygroundTtsRoute: typeof PlaygroundTtsRoute
  PlaygroundVideoRoute: typeof PlaygroundVideoRoute
  HubIndexRoute: typeof HubIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installed': {
      id: '/installed'
      path: '/installed'
      fullPath: '/installed'
      preLoaderRoute: typeof InstalledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark': {
      id: '/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof BenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/video': {
      id: '/playground/video'
      path: '/playground/video'
      fullPath: '/playground/video'
      preLoaderRoute: typeof PlaygroundVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/tts': {
      id: '/playground/tts'
      path: '/playground/tts'
      fullPath: '/playground/tts'
      preLoaderRoute: typeof PlaygroundTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/stt': {
      id: '/playground/stt'
      path: '/playground/stt'
      fullPath: '/playground/stt'
      preLoaderRoute: typeof PlaygroundSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/image': {
      id: '/playground/image'
      path: '/playground/image'
      fullPath: '/playground/image'
      preLoaderRoute: typeof PlaygroundImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/chat': {
      id: '/playground/chat'
      path: '/playground/chat'
      fullPath: '/playground/chat'
      preLoaderRoute: typeof PlaygroundChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/audio': {
      id: '/playground/audio'
      path: '/playground/audio'
      fullPath: '/playground/audio'
      preLoaderRoute: typeof PlaygroundAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchmarkRoute: BenchmarkRoute,
  CompareRoute: CompareRoute,
  DownloadsRoute: DownloadsRoute,
  InstalledRoute: InstalledRoute,
  SettingsRoute: SettingsRoute,
  PlaygroundAudioRoute: PlaygroundAudioRoute,
  PlaygroundChatRoute: PlaygroundChatRoute,
  PlaygroundImageRoute: PlaygroundImageRoute,
  PlaygroundSttRoute: PlaygroundSttRoute,
  PlaygroundTtsRoute: PlaygroundTtsRoute,
  PlaygroundVideoRoute: PlaygroundVideoRoute,
  HubIndexRoute: HubIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
